// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDca0Q8PWOBEmeAv1azP4T_7MgfamGAjtA',
    appId: '1:1091334843791:android:5a2c2a2d4cadf80e246ffa',
    messagingSenderId: '1091334843791',
    projectId: 'tasky-1da22',
    storageBucket: 'tasky-1da22.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyxZS6cc1SB2mVYnx7yQdJ7EGzQf2iTGc',
    appId: '1:1091334843791:ios:3e2bbba2cb07680f246ffa',
    messagingSenderId: '1091334843791',
    projectId: 'tasky-1da22',
    storageBucket: 'tasky-1da22.firebasestorage.app',
    iosBundleId: 'com.example.tasky',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAyxZS6cc1SB2mVYnx7yQdJ7EGzQf2iTGc',
    appId: '1:1091334843791:ios:3e2bbba2cb07680f246ffa',
    messagingSenderId: '1091334843791',
    projectId: 'tasky-1da22',
    storageBucket: 'tasky-1da22.firebasestorage.app',
    iosBundleId: 'com.example.tasky',
  );
}
